// <auto-generated />
using InfrastructureUF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfrastructureUF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124194033_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppUF.Domain.EstadoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capital = "Rio Branco",
                            Descricao = "Estado na Região Norte...",
                            Nome = "Acre",
                            Regiao = "Norte",
                            Sigla = "AC"
                        },
                        new
                        {
                            Id = 2,
                            Capital = "Maceió",
                            Descricao = "Estado do Nordeste...",
                            Nome = "Alagoas",
                            Regiao = "Nordeste",
                            Sigla = "AL"
                        },
                        new
                        {
                            Id = 3,
                            Capital = "Macapá",
                            Descricao = "Estado na Região Norte...",
                            Nome = "Amapá",
                            Regiao = "Norte",
                            Sigla = "AP"
                        },
                        new
                        {
                            Id = 4,
                            Capital = "Manaus",
                            Descricao = "O maior estado do Brasil...",
                            Nome = "Amazonas",
                            Regiao = "Norte",
                            Sigla = "AM"
                        },
                        new
                        {
                            Id = 5,
                            Capital = "Salvador",
                            Descricao = "Estado do Nordeste, centro da cultura afro-brasileira...",
                            Nome = "Bahia",
                            Regiao = "Nordeste",
                            Sigla = "BA"
                        },
                        new
                        {
                            Id = 6,
                            Capital = "Fortaleza",
                            Descricao = "Estado nordestino conhecido pelas suas famosas dunas...",
                            Nome = "Ceará",
                            Regiao = "Nordeste",
                            Sigla = "CE"
                        },
                        new
                        {
                            Id = 7,
                            Capital = "Brasília",
                            Descricao = "Onde se localiza Brasília...",
                            Nome = "Distrito Federal",
                            Regiao = "Centro-Oeste",
                            Sigla = "DF"
                        },
                        new
                        {
                            Id = 8,
                            Capital = "Vitória",
                            Descricao = "Estado da Região Sudeste...",
                            Nome = "Espírito Santo",
                            Regiao = "Sudeste",
                            Sigla = "ES"
                        },
                        new
                        {
                            Id = 9,
                            Capital = "Goiânia",
                            Descricao = "Localizado no Centro-Oeste...",
                            Nome = "Goiás",
                            Regiao = "Centro-Oeste",
                            Sigla = "GO"
                        },
                        new
                        {
                            Id = 10,
                            Capital = "São Luís",
                            Descricao = "Estado do Nordeste com o Parque Nacional dos Lençóis Maranhenses...",
                            Nome = "Maranhão",
                            Regiao = "Nordeste",
                            Sigla = "MA"
                        },
                        new
                        {
                            Id = 11,
                            Capital = "Cuiabá",
                            Descricao = "Estado do Centro-Oeste...",
                            Nome = "Mato Grosso",
                            Regiao = "Centro-Oeste",
                            Sigla = "MT"
                        },
                        new
                        {
                            Id = 12,
                            Capital = "Campo Grande",
                            Descricao = "Famoso pela região do Pantanal...",
                            Nome = "Mato Grosso do Sul",
                            Regiao = "Centro-Oeste",
                            Sigla = "MS"
                        },
                        new
                        {
                            Id = 13,
                            Capital = "Belo Horizonte",
                            Descricao = "Estado da Região Sudeste...",
                            Nome = "Minas Gerais",
                            Regiao = "Sudeste",
                            Sigla = "MG"
                        },
                        new
                        {
                            Id = 14,
                            Capital = "Belém",
                            Descricao = "Estado da Região Norte...",
                            Nome = "Pará",
                            Regiao = "Norte",
                            Sigla = "PA"
                        },
                        new
                        {
                            Id = 15,
                            Capital = "João Pessoa",
                            Descricao = "Estado nordestino famoso pelo ponto mais oriental das Américas...",
                            Nome = "Paraíba",
                            Regiao = "Nordeste",
                            Sigla = "PB"
                        },
                        new
                        {
                            Id = 16,
                            Capital = "Curitiba",
                            Descricao = "Estado da Região Sul...",
                            Nome = "Paraná",
                            Regiao = "Sul",
                            Sigla = "PR"
                        },
                        new
                        {
                            Id = 17,
                            Capital = "Recife",
                            Descricao = "Estado do Nordeste...",
                            Nome = "Pernambuco",
                            Regiao = "Nordeste",
                            Sigla = "PE"
                        },
                        new
                        {
                            Id = 18,
                            Capital = "Teresina",
                            Descricao = "Estado do Nordeste...",
                            Nome = "Piauí",
                            Regiao = "Nordeste",
                            Sigla = "PI"
                        },
                        new
                        {
                            Id = 19,
                            Capital = "Rio de Janeiro",
                            Descricao = "Famoso no mundo todo por suas praias...",
                            Nome = "Rio de Janeiro",
                            Regiao = "Sudeste",
                            Sigla = "RJ"
                        },
                        new
                        {
                            Id = 20,
                            Capital = "Natal",
                            Descricao = "Estado nordestino com o litoral repleto de dunas...",
                            Nome = "Rio Grande do Norte",
                            Regiao = "Nordeste",
                            Sigla = "RN"
                        },
                        new
                        {
                            Id = 21,
                            Capital = "Porto Alegre",
                            Descricao = "Estado da Região Sul...",
                            Nome = "Rio Grande do Sul",
                            Regiao = "Sul",
                            Sigla = "RS"
                        },
                        new
                        {
                            Id = 22,
                            Capital = "Porto Velho",
                            Descricao = "Estado da Região Norte...",
                            Nome = "Rondônia",
                            Regiao = "Norte",
                            Sigla = "RO"
                        },
                        new
                        {
                            Id = 23,
                            Capital = "Boa Vista",
                            Descricao = "O estado mais setentrional do Brasil...",
                            Nome = "Roraima",
                            Regiao = "Norte",
                            Sigla = "RR"
                        },
                        new
                        {
                            Id = 24,
                            Capital = "Florianópolis",
                            Descricao = "Estado da Região Sul...",
                            Nome = "Santa Catarina",
                            Regiao = "Sul",
                            Sigla = "SC"
                        },
                        new
                        {
                            Id = 25,
                            Capital = "São Paulo",
                            Descricao = "O estado mais populoso e rico do Brasil...",
                            Nome = "São Paulo",
                            Regiao = "Sudeste",
                            Sigla = "SP"
                        },
                        new
                        {
                            Id = 26,
                            Capital = "Aracaju",
                            Descricao = "O menor estado do Brasil...",
                            Nome = "Sergipe",
                            Regiao = "Nordeste",
                            Sigla = "SE"
                        },
                        new
                        {
                            Id = 27,
                            Capital = "Palmas",
                            Descricao = "O estado mais jovem do Brasil...",
                            Nome = "Tocantins",
                            Regiao = "Norte",
                            Sigla = "TO"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
