// <auto-generated />
using InfrastructureUF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfrastructureUF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppUF.Domain.EstadoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capital = "Rio Branco",
                            Descricao = "Estado na Região Norte, conhecido pela Floresta Amazônica e pela extração de borracha.",
                            Nome = "Acre",
                            Regiao = "Norte",
                            Sigla = "AC"
                        },
                        new
                        {
                            Id = 2,
                            Capital = "Maceió",
                            Descricao = "Estado do Nordeste, famoso pelas praias de águas claras e coqueirais.",
                            Nome = "Alagoas",
                            Regiao = "Nordeste",
                            Sigla = "AL"
                        },
                        new
                        {
                            Id = 3,
                            Capital = "Macapá",
                            Descricao = "Estado na Região Norte, com grande biodiversidade e atravessado pela linha do Equador.",
                            Nome = "Amapá",
                            Regiao = "Norte",
                            Sigla = "AP"
                        },
                        new
                        {
                            Id = 4,
                            Capital = "Manaus",
                            Descricao = "O maior estado do Brasil, coberto em grande parte pela Floresta Amazônica e cortado pelo Rio Amazonas.",
                            Nome = "Amazonas",
                            Regiao = "Norte",
                            Sigla = "AM"
                        },
                        new
                        {
                            Id = 5,
                            Capital = "Salvador",
                            Descricao = "Estado do Nordeste, centro da cultura afro-brasileira, com forte influência na culinária e música.",
                            Nome = "Bahia",
                            Regiao = "Nordeste",
                            Sigla = "BA"
                        },
                        new
                        {
                            Id = 6,
                            Capital = "Fortaleza",
                            Descricao = "Estado nordestino conhecido pelas suas famosas dunas e praias, como Jericoacoara.",
                            Nome = "Ceará",
                            Regiao = "Nordeste",
                            Sigla = "CE"
                        },
                        new
                        {
                            Id = 7,
                            Capital = "Brasília",
                            Descricao = "Onde se localiza Brasília, capital federal do Brasil, planejada por Lúcio Costa e Oscar Niemeyer.",
                            Nome = "Distrito Federal",
                            Regiao = "Centro-Oeste",
                            Sigla = "DF"
                        },
                        new
                        {
                            Id = 8,
                            Capital = "Vitória",
                            Descricao = "Estado da Região Sudeste, possui litoral extenso e é um grande produtor de café e minério.",
                            Nome = "Espírito Santo",
                            Regiao = "Sudeste",
                            Sigla = "ES"
                        },
                        new
                        {
                            Id = 9,
                            Capital = "Goiânia",
                            Descricao = "Localizado no Centro-Oeste, conhecido pelo ecoturismo na Chapada dos Veadeiros e forte agropecuária.",
                            Nome = "Goiás",
                            Regiao = "Centro-Oeste",
                            Sigla = "GO"
                        },
                        new
                        {
                            Id = 10,
                            Capital = "São Luís",
                            Descricao = "Estado do Nordeste com o Parque Nacional dos Lençóis Maranhenses, de beleza singular.",
                            Nome = "Maranhão",
                            Regiao = "Nordeste",
                            Sigla = "MA"
                        },
                        new
                        {
                            Id = 11,
                            Capital = "Cuiabá",
                            Descricao = "Estado do Centro-Oeste que abriga parte da Amazônia, Cerrado e a região do Pantanal.",
                            Nome = "Mato Grosso",
                            Regiao = "Centro-Oeste",
                            Sigla = "MT"
                        },
                        new
                        {
                            Id = 12,
                            Capital = "Campo Grande",
                            Descricao = "Famoso pela região do Pantanal, um dos maiores centros de biodiversidade do planeta.",
                            Nome = "Mato Grosso do Sul",
                            Regiao = "Centro-Oeste",
                            Sigla = "MS"
                        },
                        new
                        {
                            Id = 13,
                            Capital = "Belo Horizonte",
                            Descricao = "Estado da Região Sudeste, conhecido pela culinária, cidades históricas coloniais e serras.",
                            Nome = "Minas Gerais",
                            Regiao = "Sudeste",
                            Sigla = "MG"
                        },
                        new
                        {
                            Id = 14,
                            Capital = "Belém",
                            Descricao = "Estado da Região Norte, importante polo de recursos minerais e com forte presença da cultura amazônica.",
                            Nome = "Pará",
                            Regiao = "Norte",
                            Sigla = "PA"
                        },
                        new
                        {
                            Id = 15,
                            Capital = "João Pessoa",
                            Descricao = "Estado nordestino famoso pelo ponto mais oriental das Américas, a Ponta do Seixas.",
                            Nome = "Paraíba",
                            Regiao = "Nordeste",
                            Sigla = "PB"
                        },
                        new
                        {
                            Id = 16,
                            Capital = "Curitiba",
                            Descricao = "Estado da Região Sul, onde estão localizadas as famosas Cataratas do Iguaçu.",
                            Nome = "Paraná",
                            Regiao = "Sul",
                            Sigla = "PR"
                        },
                        new
                        {
                            Id = 17,
                            Capital = "Recife",
                            Descricao = "Estado do Nordeste, berço de cidades históricas como Olinda e o Porto Digital no Recife.",
                            Nome = "Pernambuco",
                            Regiao = "Nordeste",
                            Sigla = "PE"
                        },
                        new
                        {
                            Id = 18,
                            Capital = "Teresina",
                            Descricao = "Estado do Nordeste, conhecido pelo Parque Nacional Serra da Capivara, patrimônio da UNESCO.",
                            Nome = "Piauí",
                            Regiao = "Nordeste",
                            Sigla = "PI"
                        },
                        new
                        {
                            Id = 19,
                            Capital = "Rio de Janeiro",
                            Descricao = "Famoso no mundo todo por suas praias, o Cristo Redentor e o Pão de Açúcar. Sede de grande metrópole.",
                            Nome = "Rio de Janeiro",
                            Regiao = "Sudeste",
                            Sigla = "RJ"
                        },
                        new
                        {
                            Id = 20,
                            Capital = "Natal",
                            Descricao = "Estado nordestino com o litoral repleto de dunas e salinas, com destaque para Natal.",
                            Nome = "Rio Grande do Norte",
                            Regiao = "Nordeste",
                            Sigla = "RN"
                        },
                        new
                        {
                            Id = 21,
                            Capital = "Porto Alegre",
                            Descricao = "Estado da Região Sul, com forte influência da cultura gaúcha e grande produção de vinhos.",
                            Nome = "Rio Grande do Sul",
                            Regiao = "Sul",
                            Sigla = "RS"
                        },
                        new
                        {
                            Id = 22,
                            Capital = "Porto Velho",
                            Descricao = "Estado da Região Norte com grande desenvolvimento da agropecuária e fronteira com a Bolívia.",
                            Nome = "Rondônia",
                            Regiao = "Norte",
                            Sigla = "RO"
                        },
                        new
                        {
                            Id = 23,
                            Capital = "Boa Vista",
                            Descricao = "O estado mais setentrional do Brasil, conhecido pelo Monte Roraima e áreas indígenas.",
                            Nome = "Roraima",
                            Regiao = "Norte",
                            Sigla = "RR"
                        },
                        new
                        {
                            Id = 24,
                            Capital = "Florianópolis",
                            Descricao = "Estado da Região Sul, com belas praias e forte influência da colonização europeia.",
                            Nome = "Santa Catarina",
                            Regiao = "Sul",
                            Sigla = "SC"
                        },
                        new
                        {
                            Id = 25,
                            Capital = "São Paulo",
                            Descricao = "O estado mais populoso e rico do Brasil, centro financeiro e industrial da América Latina.",
                            Nome = "São Paulo",
                            Regiao = "Sudeste",
                            Sigla = "SP"
                        },
                        new
                        {
                            Id = 26,
                            Capital = "Aracaju",
                            Descricao = "O menor estado do Brasil, conhecido pelas praias e pela cultura ribeirinha no Rio São Francisco.",
                            Nome = "Sergipe",
                            Regiao = "Nordeste",
                            Sigla = "SE"
                        },
                        new
                        {
                            Id = 27,
                            Capital = "Palmas",
                            Descricao = "O estado mais jovem do Brasil, criado em 1988, com o Parque Estadual do Jalapão.",
                            Nome = "Tocantins",
                            Regiao = "Norte",
                            Sigla = "TO"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
